data_folder: data

start_date: 2023-10-01   # 2023-10-01
end_date: 2024-10-01   # 2024-12-30

sequence_length: 28
timestep_hours: 4
window_step: 4

regions:
  # - ap-northeast-1
  # - ap-northeast-2 
  # - ap-northeast-3
  # - ap-south-1
  # - ap-southeast-1
  # - ap-southeast-2
  # - ca-central-1
  - eu-central-1
  # - eu-north-1
  # - eu-west-1
  # - eu-west-2
  # - eu-west-3
  # - sa-east-1
  # - us-east-1
  # - us-east-2
  # - us-west-1
  # - us-west-2
product_description: Linux/UNIX

target_col: spot_price
time_col: price_timestamp
categorical_cols:
  # - region
  - av_zone
  - instance_family
  - generation
  - size

multicategorical_cols:
  - modifiers
  - architectures

numerical_cols:
  # - on_demand_price
  # - hour_sin
  # - hour_cos
  - dow_sin
  - dow_cos
  - dom_sin
  - dom_cos
  # - doy_sin
  # - doy_cos

time_features:
  # - dayofweek
  # - dayofmonth
