dataset_config:
  batch_size: 128
  instance_features:
  - generation
  - modifiers
  - size
  time_features:
  - dayofweek
  - dayofmonth
dataset_features:
  data_folder: data
  end_date: 2025-04-21
  instance_filters:
    architectures:
    - x86_64
    generation:
    - 5
    - 6
    - 7
    - 8
    instance_family:
    - c
    metal: false
    product_description:
    - Linux/UNIX
  regions:
  - eu-north-1
  start_date: 2024-01-01
  target_col: spot_price
  time_col: price_timestamp
evaluate_config:
  batch_size: 32
  significance_threshold: 0.02
loss_config:
  loss_type: TrendFocusLoss
  mse_weight: 1.0
  significant_threshold: 0.02
  smoothing_factor: 10.0
model_config:
  hidden_size: 64
  instance_feature_size: 20
  model_type: FeatureSeq2Seq
  num_layers: 2
  output_scale: 1.0
  shuffle_buffer: 1000
  teacher_forcing_ratio: 0.7
  time_feature_size: 120
model_name: featureseq2seq-4h-2d
sequence_config:
  evaluation_days: 1
  model_pred_days: 2
  prediction_length_days: 20
  sequence_length_days: 20
  timestep_hours: 4
  window_step_days: 0.5
training_hyperparams:
  div_factor: 10
  epochs: 20
  learning_rate: 1e-4
  max_learning_rate: 2e-6
  patience: 5
  pct_start: 0.2
  weight_decay: 5e-5
